nanoseconds(x::NanoTime{T}) where T = value(x)
microseconds(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_MICROSECOND)
milliseconds(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_MILLISECOND)
seconds(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_SECOND)
minutes(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_MINUTE)
hours(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_HOUR)
days(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_DAY)
weeks(x::NanoTime{T}) where T = fld(value(x), NANOSECONDS_PER_WEEK)

Nanoseconds(x::NanoTime{T}) where T = Nanosecond(nanoseconds(x))
Microseconds(x::NanoTime{T}) where T = Microsecond(microseconds(x))
Milliseconds(x::NanoTime{T}) where T = Millisecond(milliseconds(x))
Seconds(x::NanoTime{T}) where T = Second(seconds(x))
Minutes(x::NanoTime{T}) where T = Minute(minute(x))
Hours(x::NanoTime{T}) where T = Hour(hours(x))
Days(x::NanoTime{T}) where T = Day(days(x))
Weeks(x::NanoTime{T}) where T = Week(weeks(x))
