const QUARTERS_PER_YEAR  = IntTime(4)
const MONTHS_PER_QUARTER = IntTime(3)
const MONTHS_PER_YEAR    = QUARTERS_PER_YEAR * MONTHS_PER_QUARTER

const DAYS_PER_WEEK      = IntTime(7)
const HOURS_PER_DAY      = IntTime(24)
const MINUTES_PER_HOUR   = IntTime(60)
const SECONDS_PER_MINUTE = IntTime(60)
const MILLISECONDS_PER_SECOND      = IntTime(1_000)
const MICROSECONDS_PER_MILLISECOND = IntTime(1_000)
const NANOSECONDS_PER_MICROSECOND  = IntTime(1_000)

const HOURS_PER_WEEK   = DAYS_PER_WEEK * HOURS_PER_DAY
const MINUTES_PER_WEEK = HOURS_PER_WEEK * MINUTES_PER_HOUR
const SECONDS_PER_WEEK = MINUTES_PER_WEEK * SECONDS_PER_MINUTE
const MILLISECONDS_PER_WEEK = SECONDS_PER_WEEK * MILLISECONDS_PER_SECOND
const MICROSECONDS_PER_WEEK = MILLISECONDS_PER_WEEK * MICROSECONDS_PER_MILLISECOND
const NANOSECONDS_PER_WEEK  = MICROSECONDS_PER_WEEK * NANOSECONDS_PER_MICROSECOND

const MINUTES_PER_DAY = HOURS_PER_DAY * MINUTES_PER_HOUR
const SECONDS_PER_DAY = MINUTES_PER_DAY * SECONDS_PER_MINUTE
const MILLISECONDS_PER_DAY = SECONDS_PER_DAY * MILLISECONDS_PER_SECOND
const MICROSECONDS_PER_DAY = MILLISECONDS_PER_DAY * MICROSECONDS_PER_MILLISECOND
const NANOSECONDS_PER_DAY  = MICROSECONDS_PER_DAY * NANOSECONDS_PER_MICROSECOND

const SECONDS_PER_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE
const MILLISECONDS_PER_HOUR = SECONDS_PER_HOUR * MILLISECONDS_PER_SECOND
const MICROSECONDS_PER_HOUR = MILLISECONDS_PER_HOUR * MICROSECONDS_PER_MILLISECOND
const NANOSECONDS_PER_HOUR  = MICROSECONDS_PER_HOUR * NANOSECONDS_PER_MICROSECOND

const MILLISECONDS_PER_MINUTE = SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND
const MICROSECONDS_PER_MINUTE = MILLISECONDS_PER_MINUTE * MICROSECONDS_PER_MILLISECOND
const NANOSECONDS_PER_MINUTE  = MICROSECONDS_PER_MINUTE * NANOSECONDS_PER_MICROSECOND

const MICROSECONDS_PER_SECOND = MILLISECONDS_PER_SECOND * MICROSECONDS_PER_MILLISECOND
const NANOSECONDS_PER_SECOND  = MICROSECONDS_PER_SECOND * NANOSECONDS_PER_MICROSECOND

const NANOSECONDS_PER_MILLISECOND  = MILLISECONDS_PER_SECOND * NANOSECONDS_PER_MICROSECOND

const ZEROHOUR = parse(Base.Dates.Time, "00:00:00")
