nanoseconds(x::NanoSpan{T}) where T = value(x)
microseconds(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_MICROSECOND)
milliseconds(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_MILLISECOND)
seconds(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_SECOND)
minutes(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_MINUTE)
hours(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_HOUR)
days(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_DAY)
weeks(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_WEEK)

Nanoseconds(x::NanoSpan{T}) where T = Nanosecond(nanoseconds(x))
Microseconds(x::NanoSpan{T}) where T = Microsecond(microseconds(x))
Milliseconds(x::NanoSpan{T}) where T = Millisecond(milliseconds(x))
Seconds(x::NanoSpan{T}) where T = Second(seconds(x))
Minutes(x::NanoSpan{T}) where T = Minute(minutes(x))
Hours(x::NanoSpan{T}) where T = Hour(hours(x))
Days(x::NanoSpan{T}) where T = Day(days(x))
Weeks(x::NanoSpan{T}) where T = Week(weeks(x))

nanosecond(x::NanoSpan{T}) where T = mod(nanoseconds(x), NANOSECONDS_PER_MICROSECOND)
microsecond(x::NanoSpan{T}) where T = mod(microseconds(x), MICROSECONDS_PER_MILLISECOND)
millisecond(x::NanoSpan{T}) where T = mod(milliseconds(x), MILLISECONDS_PER_SECOND)
second(x::NanoSpan{T}) where T = mod(seconds(x), SECONDS_PER_MINUTE)
minute(x::NanoSpan{T}) where T = mod(minutes(x), MINUTES_PER_HOUR)
hour(x::NanoSpan{T}) where T = mod(hours(x), HOURS_PER_DAY)
day(x::NanoSpan{T}) where T = days(x)
week(x::NanoSpan{T}) where T = weeks(x)

Nanosecond(x::NanoSpan{T}) where T = Nanosecond(nanosecond(x))
Microsecond(x::NanoSpan{T}) where T = Microsecond(microsecond(x))
Millisecond(x::NanoSpan{T}) where T = Millisecond(millisecond(x))
Second(x::NanoSpan{T}) where T = Second(second(x))
Minute(x::NanoSpan{T}) where T = Minute(minute(x))
Hour(x::NanoSpan{T}) where T = Hour(hour(x))
Day(x::NanoSpan{T}) where T = Day(day(x))
Week(x::NanoSpan{T}) where T = Week(week(x))
