nanoseconds(x::NanoSpan{T}) where T = value(x)
microseconds(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_MICROSECOND)
milliseconds(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_MILLISECOND)
seconds(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_SECOND)
minutes(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_MINUTE)
hours(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_HOUR)
NANOSECONDS_PER_DAY)
weeks(x::NanoSpan{T}) where T = fld(value(x), NANOSECONDS_PER_WEEK)

Nadays(x::NanoSpan{T}) where T = fld(value(x), noseconds(x::NanoSpan{T}) where T = Nanosecond(nanoseconds(x))
Microseconds(x::NanoSpan{T}) where T = Microsecond(microseconds(x))
Milliseconds(x::NanoSpan{T}) where T = Millisecond(milliseconds(x))
Seconds(x::NanoSpan{T}) where T = Second(seconds(x))
Minutes(x::NanoSpan{T}) where T = Minute(minute(x))
Hours(x::NanoSpan{T}) where T = Hour(hours(x))
Days(x::NanoSpan{T}) where T = Day(days(x))
Weeks(x::NanoSpan{T}) where T = Week(weeks(x))
